### ISSUE TITLE
Update to use `reth 1.0` matiching or compatible depenancies

### ISSUE THREAD

**Issue by nuke-web3** [risc0/zeth#110]
See https://www.paradigm.xyz/2024/06/reth-prod via https://x.com/gakonst/status/1805920383390154845

Release https://github.com/paradigmxyz/reth/releases/tag/v1.0.0

IIUC, we don't use `reth` itself here. What I propose is updating to match the dependencies to make this repo fully compatible with `reth 1.0` (if that makes sense?).

**Comment by nicholas-1vbw** [comment]
I've tried to upgrade revm/sha to compatble version with reth.
1. Most types from revm-primitives have been replaced by alloy, which introduces many mismatch type error in `zeth-lib`.
2. Recent version of revm needs 1.79, see https://github.com/risc0/risc0/issues/2088

Updating to compatible dependencies requires additional effort.

**Comment by mahmudsudo** [comment]
can i take on this ?
