### ISSUE TITLE
Discussion on whether the "base_fee_per_gas" field can be empty

### ISSUE THREAD

**Issue by RuiQi857** [risc0/zeth#120]
For the block header structure before the Ethereum London upgrade, there is no base_fee_per_gas field. But I found that the base_fee_per_gas field in zeth is not Option, which will cause problems when processing blocks before the London upgrade.
<img width="926" alt="image" src="https://github.com/user-attachments/assets/118c10a0-af67-45cc-b833-f003fa7b900b">

**Comment by hashcashier** [comment]
Fixed by #115
