### ISSUE TITLE
L1 contracts?

### ISSUE THREAD

**Issue by GopherJ** [risc0/zeth#47]
seems L1 contracts are not ready?

**Comment by intoverflow** [comment]
Which L1 contract are you referring to?

**Comment by GopherJ** [comment]
hi @intoverflow I'm talking about the main zkEVM contracts which store user assets, blockchain stateroots etc. Isn't zeth a layer2 zkEVM?

**Comment by intoverflow** [comment]
It is not an L2. For more information, see here: https://www.risczero.com/news/zeth-release
