### ISSUE TITLE
cargo build failed when dependce risc0-zkvm of crates-io

### ISSUE THREAD

**Issue by yyjia** [risc0/zeth#58]
Although it can be bypassed by
```
[patch.crates-io]
risc0-zkvm = { git = "https://github.com/risc0/risc0", tag = "v0.19.1" }
```

**Comment by yyjia** [comment]
> Although it can be bypassed by
> 
> ```
> [patch.crates-io]
> risc0-zkvm = { git = "https://github.com/risc0/risc0", tag = "v0.19.1" }
> ```

admin@starlink01:~/devel/zeth$ cargo build
   Compiling zeth-guests v0.1.0 (/home/admin/devel/zeth/guests)
   Compiling risc0-zkvm v0.19.1
   Compiling zeth-testeth v0.1.0 (/home/admin/devel/zeth/testing/ef-tests)
test-guest: Starting build for riscv32im-risc0-zkvm-elf-zkvm, zeth-testeth(build), zeth-guests(build)                                                                                                                      
error: expected one of `)`, `,`, `.`, `?`, or an operator, found `rOpts`
   --> /home/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.19.1/src/host/server/prove/mod.rs:116:58
    |
116 |         let prover = get_prover_server(&Provedefault = []rOpts::default())?;
    |                                                          -^^^^
    |                                                          |
    |                                                          expected one of `)`, `,`, `.`, `?`, or an operator
    |                                                          help: missing `,`

eth-block: Starting build for riscv32im-risc0-zkvm-elf0-zkvm, zeth-testeth(build), zeth-guests(build)                                                                                                                      
eth-block:     Blocking waiting for file lock on package cache
test-guest:     Blocking waiting for file lock on package cache
eth-block:     Blocking waiting for file lock on package cache
test-guest:     Blocking waiting for file lock on package cache
error[E0425]: cannot find value `Provedefault` in this scope
   --> /home/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.19.1/src/host/server/prove/mod.rs:116:41
    |
116 |         let prover = get_prover_server(&Provedefault = []rOpts::default())?;
    |                                         ^^^^^^^^^^^^ not found in this scope

eth-block:     Blocking waiting for file lock on package cachezeth-testeth(build), zeth-guests(build)                                                                                                                      
test-guest:     Blocking waiting for file lock on package cache
test-guest:     Blocking waiting for file lock on build directory
eth-block:     Finished release [optimized] target(s) in 0.28s
test-guest:     Finished release [optimized] target(s) in 0.31s
op-block: Starting build for riscv32im-risc0-zkvm-elf
op-block:     Finished release [optimized] target(s) in 0.14s zeth-guests(build)                                                                                                                                           
error[E0070]: invalid left-hand side of assignment
   --> /home/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.19.1/src/host/server/prove/mod.rs:116:54
    |
116 |         let prover = get_prover_server(&Provedefault = []rOpts::default())?;
    |                                        ------------- ^
    |                                        |
    |                                        cannot assign to this expression

error[E0433]: failed to resolve: use of undeclared crate or module `rOpts`
   --> /home/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.19.1/src/host/server/prove/mod.rs:116:58
    |
116 |         let prover = get_prover_server(&Provedefault = []rOpts::default())?;
    |                                                          ^^^^^ use of undeclared crate or module `rOpts`

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /home/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.19.1/src/host/server/prove/mod.rs:116:22
    |
116 |         let prover = get_prover_server(&Provedefault = []rOpts::default())?;

**Comment by Wollac** [comment]
I think you have accidentally modified the local `risc0-zkvm` sources that cargo downloads to `/home/admin/.cargo/registry/src/`. The specific correct line is:
```rust
let prover = get_prover_server(&ProverOpts::default())?;
```
So, some parts got modified for your installation. 

Either reverting this line manually or removing the content of the `cargo` cache under `/home/admin/.cargo/registry` will resolve your problem.
